version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: harvest_db
      POSTGRES_USER: harvest_user
      POSTGRES_PASSWORD: harvest_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U harvest_user -d harvest_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # HARVEST Backend API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://harvest_user:harvest_password@postgres:5432/harvest_db
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=True
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker for Background Tasks
  celery:
    build: .
    command: celery -A app.core.scheduler worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://harvest_user:harvest_password@postgres:5432/harvest_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  # Celery Beat for Scheduled Tasks
  celery-beat:
    build: .
    command: celery -A app.core.scheduler beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://harvest_user:harvest_password@postgres:5432/harvest_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

volumes:
  postgres_data:
  redis_data: